services:
  - type: web
    name: inh-multiagents
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT main_fastapi:app
    autoDeploy: true
